In [1]:
import numpy as np


In [2]:
np

<module 'numpy' from '/home/brandon/anaconda3/lib/python3.9/site-packages/numpy/__init__.py'>

Creating Arrays w/ Numpy


In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [5]:
np.full(10, 5)

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [6]:
np.array([1, 2, 3, 4, 5, 10, 12, 17, 21]) 

array([ 1,  2,  3,  4,  5, 10, 12, 17, 21])

In [7]:
a = np.array([1, 2, 3, 4, 5, 10, 12, 17, 21])

In [8]:
a[2] = 100

In [9]:
a


array([  1,   2, 100,   4,   5,  10,  12,  17,  21])

In [10]:
np.arange(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

In [12]:
np.linspace(0, 1, 11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

Creating Multi-dementional arrays

In [13]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [14]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [15]:
np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
n = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [17]:
n[0, 1] 

2

In [18]:
n[1, 2] = 100

In [19]:
n

array([[  1,   2,   3],
       [  4,   5, 100],
       [  7,   8,   9]])

In [20]:
n[2]

array([7, 8, 9])

In [21]:
n[2] = [1, 1, 1,]

In [22]:
n

array([[  1,   2,   3],
       [  4,   5, 100],
       [  1,   1,   1]])

In [23]:
n[:, 0]

array([1, 4, 1])

In [24]:
n[:, 2] = [99, 99, 99]  

In [25]:
n

array([[ 1,  2, 99],
       [ 4,  5, 99],
       [ 1,  1, 99]])

Randomly generated arrays

In [26]:
np.random.rand(5, 2)

array([[0.97895231, 0.98063175],
       [0.90277287, 0.02486055],
       [0.68253946, 0.89904843],
       [0.2712709 , 0.69779141],
       [0.87352731, 0.5942934 ]])

In [27]:
np.random.rand(5, 2, 2)

array([[[0.7750736 , 0.51032689],
        [0.64256892, 0.87006647]],

       [[0.87901065, 0.32620372],
        [0.80676902, 0.3004426 ]],

       [[0.8706619 , 0.80632131],
        [0.00166727, 0.51876715]],

       [[0.72486052, 0.92841759],
        [0.45514184, 0.27179193]],

       [[0.08371095, 0.79218273],
        [0.45016156, 0.03930263]]])

In [28]:
np.random.seed(2)
np.random.rand(5, 2)

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [29]:
np.random.seed(2)
np.random.randn(5, 2)

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [30]:
np.random.seed(2)
100 * np.random.rand(5, 2)

array([[43.59949021,  2.59262318],
       [54.96624779, 43.53223926],
       [42.03678021, 33.0334821 ],
       [20.4648634 , 61.92709664],
       [29.96546737, 26.68272751]])

In [31]:
np.random.seed(2)
np.random.randint(low=0, high=100, size=(5, 2))

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]])

Element-wise operations

In [32]:
a = np.arange(5)

In [33]:
a + 1 

array([1, 2, 3, 4, 5])

In [34]:
a * 2

array([0, 2, 4, 6, 8])

In [35]:
a * 100

array([  0, 100, 200, 300, 400])

In [36]:
(10 + (a * 2))

array([10, 12, 14, 16, 18])

In [37]:
(10 + (a * 2)) ** 2/ 100

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [38]:
b = (10 + (a * 2)) ** 2/ 100

In [39]:
a + b

array([1.  , 2.44, 3.96, 5.56, 7.24])

In [40]:
a / b + 10

array([10.        , 10.69444444, 11.02040816, 11.171875  , 11.2345679 ])

Comparison operations

In [41]:
a >= 2

array([False, False,  True,  True,  True])

In [42]:
a > b

array([False, False,  True,  True,  True])

In [43]:
a[a > b]

array([2, 3, 4])

Summarizing operations

In [44]:
a.min(  )

0

In [45]:
a.max()

4

In [46]:
a.mean()

2.0

In [47]:
a.std()

1.4142135623730951

Vector operations

In [48]:
u = np.array([2, 4, 5, 6])

In [49]:
2 * u

array([ 4,  8, 10, 12])

In [50]:
v = np.array([1, 0, 0, 2])

In [51]:
u * v

array([ 2,  0,  0, 12])

In [54]:
u // v

/tmp/ipykernel_307449/3841643255.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  u // v


array([2, 0, 0, 3])

In [56]:
(u * v) + 2 ** 2

array([ 6,  4,  4, 16])

In [57]:
u + v

array([3, 4, 5, 8])

In [58]:
u.T

array([2, 4, 5, 6])

In [59]:
v.T

array([1, 0, 0, 2])

In [60]:
u * v

array([ 2,  0,  0, 12])

In [61]:
u.T * v 

array([ 2,  0,  0, 12])

In [62]:
v.T * u

array([ 2,  0,  0, 12])

Vector Multiplication

In [63]:
def vector_vector_multiplication(u, v):
    assert u.shape[0] == v.shape[0]
    n = u.shape[0]
    result = 0
    for i in range(n):
        result = result + u[i] * v[i]
    return result

In [64]:
vector_vector_multiplication(u, v)

14

In [65]:
u.dot(v)

14

In [66]:
U = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

In [67]:
V = np.array([
    [1, 2],
    [3, 4],
    [5, 6]
])

In [70]:
def matrix_vector_multiplication(U, v):
    assert U.shape[1] == v.shape[0]
    n = U.shape[1]
    result = np.zeros(U.shape[0])
    for i in range(n):
        result = result + U[:, i] * v[i]
    return result

In [73]:
matrix_vector_multiplication(U, V)

array([22., 64.])

In [76]:
def matrix__matrix_multiplication(U, V):
    assert U.shape[1] == V.shape[0]
    n = U.shape[1]
    result = np.zeros((U.shape[0], V.shape[1]))
    for i in range(n):
        result = result + matrix_vector_multiplication(U, V[:, i])
    return result

In [77]:
matrix_matrix_multiplication(U, V)

array([[22., 28.],
       [49., 64.]])

In [78]:
U.dot(V)

array([[22, 28],
       [49, 64]])

Identity Matrix

In [79]:
np.eye(10   )

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [81]:
I = np.eye(3)   

In [82]:
I


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Matrix Inverse

In [83]:
np.array([1, 2]) 

array([1, 2])

In [92]:
Vs = np.array([
    [5, 12],
    [0.5, 1]
])   
Vs

array([[ 5. , 12. ],
       [ 0.5,  1. ]])

In [93]:
Vs_inv = np.linalg.inv(Vs)
Vs_inv

array([[-1. , 12. ],
       [ 0.5, -5. ]])

In [94]:
Vs_inv.dot(Vs)

array([[1.0000000e+00, 0.0000000e+00],
       [4.4408921e-16, 1.0000000e+00]])