In [1]:
import pandas as pd
import numpy as np


In [2]:
data = 'https://raw.githubusercontent.com/alexeygrigorev/datasets/master/housing.csv'

In [3]:
!wget $data

--2023-09-24 19:43:18--  https://raw.githubusercontent.com/alexeygrigorev/datasets/master/housing.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.110.133, 185.199.108.133, 185.199.111.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.110.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1423529 (1.4M) [text/plain]
Saving to: ‘housing.csv.1’

housing.csv.1       100%[===================>]   1.36M   622KB/s    in 2.2s    

2023-09-24 19:43:21 (622 KB/s) - ‘housing.csv.1’ saved [1423529/1423529]



In [4]:
df = pd.read_csv('housing.csv')

In [5]:
df.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.23     37.88                41.0        880.0           129.0   
1    -122.22     37.86                21.0       7099.0          1106.0   
2    -122.24     37.85                52.0       1467.0           190.0   
3    -122.25     37.85                52.0       1274.0           235.0   
4    -122.25     37.85                52.0       1627.0           280.0   

   population  households  median_income  median_house_value ocean_proximity  
0       322.0       126.0         8.3252            452600.0        NEAR BAY  
1      2401.0      1138.0         8.3014            358500.0        NEAR BAY  
2       496.0       177.0         7.2574            352100.0        NEAR BAY  
3       558.0       219.0         5.6431            341300.0        NEAR BAY  
4       565.0       259.0         3.8462            342200.0        NEAR BAY

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   longitude           20640 non-null  float64
 1   latitude            20640 non-null  float64
 2   housing_median_age  20640 non-null  float64
 3   total_rooms         20640 non-null  float64
 4   total_bedrooms      20433 non-null  float64
 5   population          20640 non-null  float64
 6   households          20640 non-null  float64
 7   median_income       20640 non-null  float64
 8   median_house_value  20640 non-null  float64
 9   ocean_proximity     20640 non-null  object 
dtypes: float64(9), object(1)
memory usage: 1.6+ MB


In [7]:
df.columns

Index(['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income',
       'median_house_value', 'ocean_proximity'],
      dtype='object')

In [8]:
columns_list = list(df.columns)

In [9]:
columns_list

['longitude',
 'latitude',
 'housing_median_age',
 'total_rooms',
 'total_bedrooms',
 'population',
 'households',
 'median_income',
 'median_house_value',
 'ocean_proximity']

In [10]:
df.describe()

longitude      latitude  housing_median_age   total_rooms  \
count  20640.000000  20640.000000        20640.000000  20640.000000   
mean    -119.569704     35.631861           28.639486   2635.763081   
std        2.003532      2.135952           12.585558   2181.615252   
min     -124.350000     32.540000            1.000000      2.000000   
25%     -121.800000     33.930000           18.000000   1447.750000   
50%     -118.490000     34.260000           29.000000   2127.000000   
75%     -118.010000     37.710000           37.000000   3148.000000   
max     -114.310000     41.950000           52.000000  39320.000000   

       total_bedrooms    population    households  median_income  \
count    20433.000000  20640.000000  20640.000000   20640.000000   
mean       537.870553   1425.476744    499.539680       3.870671   
std        421.385070   1132.462122    382.329753       1.899822   
min          1.000000      3.000000      1.000000       0.499900   
25%        296.000000    787.000000    280.000000       2.563400   
50%        435.000000   1166.000000    409.000000       3.534800   
75%        647.000000   1725.000000    605.000000       4.743250   
max       6445.000000  35682.000000   6082.000000      15.000100   

       median_house_value  
count        20640.000000  
mean        206855.816909  
std         115395.615874  
min          14999.000000  
25%         119600.000000  
50%         179700.000000  
75%         264725.000000  
max         500001.000000

In [11]:
df = df[['latitude', 'longitude', 'housing_median_age', 'total_rooms', 'total_bedrooms', 'population', 'households', 'median_income', 'median_house_value', 'ocean_proximity']]

In [12]:
df.head()

latitude  longitude  housing_median_age  total_rooms  total_bedrooms  \
0     37.88    -122.23                41.0        880.0           129.0   
1     37.86    -122.22                21.0       7099.0          1106.0   
2     37.85    -122.24                52.0       1467.0           190.0   
3     37.85    -122.25                52.0       1274.0           235.0   
4     37.85    -122.25                52.0       1627.0           280.0   

   population  households  median_income  median_house_value ocean_proximity  
0       322.0       126.0         8.3252            452600.0        NEAR BAY  
1      2401.0      1138.0         8.3014            358500.0        NEAR BAY  
2       496.0       177.0         7.2574            352100.0        NEAR BAY  
3       558.0       219.0         5.6431            341300.0        NEAR BAY  
4       565.0       259.0         3.8462            342200.0        NEAR BAY

In [13]:
df_properties = df[df['ocean_proximity'].isin(['<1H OCEAN', 'INLAND'])]


In [14]:
df_properties.head()

latitude  longitude  housing_median_age  total_rooms  total_bedrooms  \
701     37.64    -121.97                32.0       1283.0           194.0   
830     37.61    -121.99                 9.0       3666.0           711.0   
859     37.57    -121.97                21.0       4342.0           783.0   
860     37.58    -121.96                15.0       3575.0           597.0   
861     37.58    -121.98                20.0       4126.0          1031.0   

     population  households  median_income  median_house_value ocean_proximity  
701       485.0       171.0         6.0574            431000.0       <1H OCEAN  
830      2341.0       703.0         4.6458            217000.0       <1H OCEAN  
859      2172.0       789.0         4.6146            247600.0       <1H OCEAN  
860      1777.0       559.0         5.7192            283500.0       <1H OCEAN  
861      2079.0       975.0         3.6832            216900.0       <1H OCEAN

In [15]:
df_properties.isnull().sum() #Total bedrooms is the answer to Questions 1

latitude                0
longitude               0
housing_median_age      0
total_rooms             0
total_bedrooms        157
population              0
households              0
median_income           0
median_house_value      0
ocean_proximity         0
dtype: int64

In [16]:
df_properties.describe() #1195 is the answer to Question 2

latitude     longitude  housing_median_age   total_rooms  \
count  15687.000000  15687.000000        15687.000000  15687.000000   
mean      35.467307   -119.217442           27.188118   2665.677312   
std        2.066387      1.780380           12.057128   2257.672743   
min       32.610000   -124.140000            1.000000      2.000000   
25%       33.940000   -121.070000           17.000000   1441.000000   
50%       34.160000   -118.370000           27.000000   2118.000000   
75%       37.340000   -117.990000           36.000000   3172.000000   
max       41.950000   -114.310000           52.000000  39320.000000   

       total_bedrooms    population    households  median_income  \
count    15530.000000  15687.000000  15687.000000   15687.000000   
mean       541.244688   1466.317205    500.916491       3.804019   
std        435.650018   1180.389908    392.759399       1.857158   
min          2.000000      3.000000      2.000000       0.499900   
25%        295.000000    802.000000    278.000000       2.520800   
50%        432.000000   1195.000000    406.000000       3.468800   
75%        645.000000   1777.000000    602.000000       4.686200   
max       6445.000000  35682.000000   6082.000000      15.000100   

       median_house_value  
count        15687.000000  
mean        191943.020017  
std         108801.077620  
min          14999.000000  
25%         111300.000000  
50%         166900.000000  
75%         241100.000000  
max         500001.000000

In [17]:
n = len(df_properties)

n_val = int(n * 0.2)
n_test = int(n * 0.2)
n_train = n - n_val - n_test

In [18]:
n, n_val + n_test + n_train

(15687, 15687)

In [19]:
df_train = df.iloc[:n_train]
df_val = df.iloc[n_train:n_train+n_val]
df_test = df.iloc[n_train+n_val:]

In [20]:
np.arange(n)
idx = np.arange(n)
np.random.seed(42)
np.random.shuffle(idx)

In [21]:
df_train = df.iloc[idx[:n_train]]
df_val = df.iloc[idx[n_train:n_train+n_val]]    
df_test = df.iloc[idx[n_train+n_val:]]

In [22]:
df_train.head()

latitude  longitude  housing_median_age  total_rooms  total_bedrooms  \
15183     33.02    -117.15                 4.0      15029.0          2279.0   
4469      34.09    -118.16                50.0       1568.0           302.0   
9316      37.98    -122.46                10.0       1325.0           189.0   
4983      34.00    -118.30                52.0       1686.0           377.0   
13154     36.81    -121.50                20.0       1345.0           230.0   

       population  households  median_income  median_house_value  \
15183      5613.0      1696.0         7.2731            450400.0   
4469       1093.0       333.0         3.1442            162100.0   
9316        427.0       162.0        12.0933            500001.0   
4983        982.0       356.0         2.0958            116400.0   
13154       731.0       217.0         4.2333            363300.0   

      ocean_proximity  
15183      NEAR OCEAN  
4469        <1H OCEAN  
9316         NEAR BAY  
4983        <1H OCEAN  
13154          INLAND

In [23]:
len(df_train), len(df_val), len(df_test)

(9413, 3137, 3137)

In [24]:
df_train = df_train.reset_index(drop=True)
df_val = df_val.reset_index(drop=True)
df_test = df_test.reset_index(drop=True)

In [25]:
y_train = np.log1p(df_train.median_house_value.values)
y_val = np.log1p(df_val.median_house_value.values)
y_test = np.log1p(df_test.median_house_value.values)

In [26]:
del df_train['median_house_value']
del df_val['median_house_value']
del df_test['median_house_value']

In [27]:
#Impute missing values with fillna
df_train = df_train.fillna(0)
df_val = df_val.fillna(0)
df_test = df_test.fillna(0)


In [28]:
#Create categorical variables and numerical variables for all dataframes
categorical_variables = ['ocean_proximity']
numerical_variables = ['latitude', 'longitude', 'housing_median_age', 'total_rooms', 'total_bedrooms', 'population', 'households', 'median_income']


In [29]:
df_train.iloc[10]

latitude                  32.84
longitude                -116.9
housing_median_age         18.0
total_rooms              3612.0
total_bedrooms            737.0
population               1864.0
households                713.0
median_income            2.7069
ocean_proximity       <1H OCEAN
Name: 10, dtype: object

In [30]:
x1 = [32.84, -116.9, 18.0, 3612.0, 737.0, 1864.0, 713.0, 2.7069]

In [31]:
w0 = 0
w = [1, 1, 1, 1, 1, 1, 1, 1]

In [32]:
def linear_regression(xi):
    n = len(xi)
    
    pred = w0
    for j in range(n):
        pred = pred + w[j] * xi[j]
        
    return pred

In [33]:
linear_regression(x1)

6862.646900000001

In [34]:
#Impute missing values with fillna using the mean
df_train_mean = df_train.fillna(df_train.mean())
df_val_mean = df_val.fillna(df_val.mean())
df_test_mean = df_test.fillna(df_test.mean())

/tmp/ipykernel_926061/3955348929.py:2: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  df_train_mean = df_train.fillna(df_train.mean())
/tmp/ipykernel_926061/3955348929.py:3: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  df_val_mean = df_val.fillna(df_val.mean())
/tmp/ipykernel_926061/3955348929.py:4: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value 

In [35]:
df_train_mean.iloc[10]

latitude                  32.84
longitude                -116.9
housing_median_age         18.0
total_rooms              3612.0
total_bedrooms            737.0
population               1864.0
households                713.0
median_income            2.7069
ocean_proximity       <1H OCEAN
Name: 10, dtype: object

In [36]:
def linear_regression(w, xi):
    pred = w[0]  # Initialize prediction with w0
    n = len(w)  # Number of features
    for j in range(1, n):  # Start from 1 to skip w0
        pred += w[j] * xi[j - 1]  # Multiply w[j] with xi[j-1] (assuming w0 is at index 0)
    return pred


In [37]:
zero_regression = linear_regression(w, x1)

In [38]:
#use regression on both dataframes using the validation set
df_val_mean.iloc[10]


latitude                   33.41
longitude                -117.61
housing_median_age          35.0
total_rooms               2556.0
total_bedrooms             404.0
population                 946.0
households                 399.0
median_income             6.1557
ocean_proximity       NEAR OCEAN
Name: 10, dtype: object

In [39]:
mean_regression = linear_regression(w, df_val_mean.iloc[10])

In [40]:
#Get the RMSE for the train and validation set
def rmse(y, y_pred):
    se = (y - y_pred) ** 2
    mse = se.mean()
    return np.sqrt(mse)

In [41]:
rmse(y_train, zero_regression), rmse(y_val, zero_regression)

(6848.879541306961, 6848.8928354260615)

In [42]:
#Start from question 4
X = [
    [4, 4, 4],
    [3, 5, 5],
    [5, 1, 1],
    [5, 4, 4],
    [7, 5, 5],
    [4, 5, 5.0000000001],
]

X = np.array(X)
X

array([[4., 4., 4.],
       [3., 5., 5.],
       [5., 1., 1.],
       [5., 4., 4.],
       [7., 5., 5.],
       [4., 5., 5.]])

In [43]:
y = [1, 2, 3, 1, 2, 3]

In [44]:
XTX = X.T.dot(X)
XTX

array([[140., 111., 111.],
       [111., 108., 108.],
       [111., 108., 108.]])

In [45]:
XTX_inv = np.linalg.inv(XTX)

In [46]:
XTX_inv.dot(X.T).dot(y)

array([ 5.17914730e-01, -8.82187500e+03,  8.82208594e+03])

In [47]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [48]:
XTX = 0.1 * np.eye(3)
XTX

array([[0.1, 0. , 0. ],
       [0. , 0.1, 0. ],
       [0. , 0. , 0.1]])

In [49]:
np.linalg.inv(XTX)

array([[10.,  0.,  0.],
       [ 0., 10.,  0.],
       [ 0.,  0., 10.]])

In [50]:
def train_linear_regression_reg(X, y, r=0.001):   
    ones = np.ones(X.shape[0])    
    X = np.column_stack([ones, X])
    
    XTX = X.T.dot(X)
    XTX = XTX + r * np.eye(XTX.shape[0])
    
    XTX_inv = np.linalg.inv(XTX)
    w_full = XTX_inv.dot(X.T).dot(y)
    
    return w_full[0], w_full[1:]

In [51]:
for r in [0, 0.000001, 0.0001, 0.001, 0.01, 0.1, 1, 5, 10]:
    w0, w = train_linear_regression_reg(X, y, r=r)
    print(r, w0, w)

0 3.733590236822238 [-4.32432222e-01 -8.13598438e+03  8.13576562e+03]
1e-06 2.7567451297618986 [-0.01801653 -0.08414136 -0.08402575]
0.0001 2.755594516549234 [-0.0178688  -0.08403217 -0.08403101]
0.001 2.74517903168005 [-0.0165316  -0.0835612  -0.08356108]
0.01 2.645264995705289 [-0.00370816 -0.07904613 -0.07904612]
0.1 1.943029756889188 [ 0.08612206 -0.04716457 -0.04716457]
1 0.557853997059341 [0.25570532 0.01948485 0.01948485]
5 0.16335417879721548 [0.27333722 0.05311796 0.05311796]
10 0.1018733421744301 [0.25298408 0.06846817 0.06846817]


In [52]:
#Use RMSE on validation set to find the best r
def prepare_X(df_val):
    df = df_val.copy()
    df = df_val.fillna(0)
    X = df_val.values
    return X

print(X)

[[4. 4. 4.]
 [3. 5. 5.]
 [5. 1. 1.]
 [5. 4. 4.]
 [7. 5. 5.]
 [4. 5. 5.]]


In [53]:
#Use prepare_X to get the X for the validation set
X_val = prepare_X(df_val)

In [54]:
#Use train_linear_regression_reg to get the w0 and w for the validation set
w0, w = train_linear_regression_reg(X, y, r=0.001)

In [55]:
#Use different seed values to see effect on RMSE
seed = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
def split_data(df, seed):
    n = len(df)
    n_val = int(n * 0.2)
    n_test = int(n * 0.2)
    n_train = n - n_val - n_test
    
    idx = np.arange(n)
    np.random.seed(seed)
    np.random.shuffle(idx)
    
    df_train = df.iloc[idx[:n_train]]
    df_val = df.iloc[idx[n_train:n_train+n_val]]
    df_test = df.iloc[idx[n_train+n_val:]]
    
    y_train = np.log1p(df_train.median_house_value.values)
    y_val = np.log1p(df_val.median_house_value.values)
    y_test = np.log1p(df_test.median_house_value.values)
    
    del df_train['median_house_value']
    del df_val['median_house_value']
    del df_test['median_house_value']
    
    return df_train, df_val, df_test, y_train, y_val, y_test

In [56]:
#Evaluate linear regression with different seeds
def train_linear_regression_reg(X, y, r=0.001):   
    ones = np.ones(X.shape[0])    
    X = np.column_stack([ones, X])
    
    XTX = X.T.dot(X)
    XTX = XTX + r * np.eye(XTX.shape[0])
    
    XTX_inv = np.linalg.inv(XTX)
    w_full = XTX_inv.dot(X.T).dot(y)
    
    return w_full[0], w_full[1:]

In [57]:
#Best seed
def rmse(y, y_pred):
    se = (y - y_pred) ** 2
    mse = se.mean()
    return np.sqrt(mse)

In [58]:
df_val.head()

latitude  longitude  housing_median_age  total_rooms  total_bedrooms  \
0     33.92    -118.24                42.0        328.0           100.0   
1     34.68    -118.12                12.0       5319.0           875.0   
2     34.10    -117.83                18.0      11026.0          1978.0   
3     32.87    -116.93                17.0       3722.0           670.0   
4     33.74    -116.41                25.0       2475.0           476.0   

   population  households  median_income ocean_proximity  
0       605.0        87.0         2.4464       <1H OCEAN  
1      2439.0       779.0         4.6629          INLAND  
2      5407.0      1923.0         4.0750          INLAND  
3      1561.0       604.0         3.6027       <1H OCEAN  
4       910.0       387.0         3.3639          INLAND

In [59]:
#remove non-numerical variables from dataframe
df_val = df_val.drop('ocean_proximity', axis=1)

In [60]:
df_val.head()

latitude  longitude  housing_median_age  total_rooms  total_bedrooms  \
0     33.92    -118.24                42.0        328.0           100.0   
1     34.68    -118.12                12.0       5319.0           875.0   
2     34.10    -117.83                18.0      11026.0          1978.0   
3     32.87    -116.93                17.0       3722.0           670.0   
4     33.74    -116.41                25.0       2475.0           476.0   

   population  households  median_income  
0       605.0        87.0         2.4464  
1      2439.0       779.0         4.6629  
2      5407.0      1923.0         4.0750  
3      1561.0       604.0         3.6027  
4       910.0       387.0         3.3639

In [61]:
import numpy as np
import pandas as pd

# Define the train_linear_regression function without regularization
def train_linear_regression(X, y):
    ones = np.ones(X.shape[0])
    X = np.column_stack([ones, X])
    XTX = X.T.dot(X)
    XTX_inv = np.linalg.inv(XTX)
    w = XTX_inv.dot(X.T).dot(y)
    return w[0], w[1:]

# Define a custom function to split the data into train, validation, and test sets
def custom_split_data(df, train_ratio=0.6, val_ratio=0.2, seed=None):
    np.random.seed(seed)  # Set a seed for reproducibility
    
    # Shuffle the data indices
    indices = np.random.permutation(len(df))
    
    # Calculate the sizes of each split
    train_size = int(train_ratio * len(df))
    val_size = int(val_ratio * len(df))
    
    # Split the indices into train, validation, and test sets
    train_indices = indices[:train_size]
    val_indices = indices[train_size:(train_size + val_size)]
    test_indices = indices[(train_size + val_size):]
    
    # Create the train, validation, and test sets
    df_train = df.iloc[train_indices]
    df_val = df.iloc[val_indices]
    df_test = df.iloc[test_indices]
    
    return df_train, df_val, df_test

# Define the prepare_X function to prepare the feature matrix X
def prepare_X(df_val):
    # Ensure that you return a valid feature matrix X
    # Fill missing values with 0 if needed
    df = df_val.fillna(0)
    
    # Identify non-numeric columns and drop them
    non_numeric_cols = df.select_dtypes(exclude=[np.number]).columns
    df = df.drop(columns=non_numeric_cols)
    
    X = df.values  # Assuming all columns in df are numeric
    return X

# Define the rmse function for calculating RMSE
def rmse(y, y_pred):
    se = (y - y_pred) ** 2
    mse = se.mean()
    return np.sqrt(mse)

# Load your dataset (replace 'your_dataset.csv' with your actual dataset file)
# df = pd.read_csv('your_dataset.csv')

# Set the seed values
seed_values = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

# Calculate RMSE scores for different seeds and collect them
scores = []

for seed in seed_values:
    df_train, df_val, df_test = custom_split_data(df, seed=seed)
    
    y_train = df_train['median_house_value'].values
    y_val = df_val['median_house_value'].values
    y_test = df_test['median_house_value'].values
    
    df_train = df_train.drop(columns=['median_house_value'])
    df_val = df_val.drop(columns=['median_house_value'])
    df_test = df_test.drop(columns=['median_house_value'])
    
    X_train = prepare_X(df_train)
    X_val = prepare_X(df_val)
    
    # Check if X_train and X_val are not None and handle missing values
    if X_train is not None and X_val is not None:
        # Train the model without regularization
        w0, w = train_linear_regression(X_train, y_train)
        
        y_pred = w0 + X_val.dot(w)
        
        score = rmse(y_val, y_pred)
        scores.append(score)
        print("Seed", seed, "RMSE:", score)
    else:
        print("Warning: X_train or X_val is None for seed", seed)

# Calculate the standard deviation of all the scores
std_deviation = np.std(scores)

# Round the result to 3 decimal digits
rounded_std_deviation = round(std_deviation, 3)

print("Standard Deviation of RMSE scores:", rounded_std_deviation)













Seed 0 RMSE: 69001.347031065
Seed 1 RMSE: 68552.17971801468
Seed 2 RMSE: 68020.97229529977
Seed 3 RMSE: 68682.27908084147
Seed 4 RMSE: 69849.4611415653
Seed 5 RMSE: 69752.60796631488
Seed 6 RMSE: 71902.50599341291
Seed 7 RMSE: 69643.15543496792
Seed 8 RMSE: 71392.58656155689
Seed 9 RMSE: 70016.31263810102
Standard Deviation of RMSE scores: 1161.95


In [62]:
#Predict with the test set
train_linear_regression(y_test, y_pred)


(204452.98777410423, array([0.00282348]))

In [63]:
#RMSE for test set
rmse(y_test, y_pred)

146645.08567927414

In [64]:
import numpy as np
import pandas as pd

# Define the train_linear_regression function with regularization (r)
def train_linear_regression(X, y, r):
    ones = np.ones(X.shape[0])
    X = np.column_stack([ones, X])
    XTX = X.T.dot(X)
    XTX = XTX + r * np.eye(XTX.shape[0])  # Add regularization term
    XTX_inv = np.linalg.inv(XTX)
    w = XTX_inv.dot(X.T).dot(y)
    return w[0], w[1:]

# Define a custom function to split the data into train, validation, and test sets
def custom_split_data(df, train_ratio=0.6, val_ratio=0.2, test_ratio=0.2, seed=None):
    np.random.seed(seed)  # Set a seed for reproducibility
    
    # Shuffle the data indices
    indices = np.random.permutation(len(df))
    
    # Calculate the sizes of each split
    train_size = int(train_ratio * len(df))
    val_size = int(val_ratio * len(df))
    test_size = len(df) - train_size - val_size
    
    # Split the indices into train, validation, and test sets
    train_indices = indices[:train_size]
    val_indices = indices[train_size:(train_size + val_size)]
    test_indices = indices[(train_size + val_size):]
    
    # Create the train, validation, and test sets
    df_train = df.iloc[train_indices]
    df_val = df.iloc[val_indices]
    df_test = df.iloc[test_indices]
    
    return df_train, df_val, df_test

# Define the prepare_X function to prepare the feature matrix X
def prepare_X(df_val):
    # Ensure that you return a valid feature matrix X
    # Fill missing values with 0
    df = df_val.fillna(0)
    
    # Identify non-numeric columns and drop them
    non_numeric_cols = df.select_dtypes(exclude=[np.number]).columns
    df = df.drop(columns=non_numeric_cols)
    
    X = df.values  # Assuming all columns in df are numeric
    return X

# Define the rmse function for calculating RMSE
def rmse(y, y_pred):
    se = (y - y_pred) ** 2
    mse = se.mean()
    return np.sqrt(mse)

# Load your dataset (replace 'your_dataset.csv' with your actual dataset file)
# df = pd.read_csv('your_dataset.csv')

# Set the seed for reproducibility
seed = 9

# Split the dataset into train, validation, and test sets using seed 9
df_train, df_val, df_test = custom_split_data(df, seed=seed)

# Combine train and validation datasets
df_train = pd.concat([df_train, df_val], axis=0)

# Extract target variables
y_train = df_train['median_house_value'].values
y_test = df_test['median_house_value'].values

# Drop target variable from datasets
df_train = df_train.drop(columns=['median_house_value'])
df_test = df_test.drop(columns=['median_house_value'])

# Prepare feature matrices X_train and X_test
X_train = prepare_X(df_train)
X_test = prepare_X(df_test)

# Regularization parameter (r)
r = 0.001

# Train the model with regularization
w0, w = train_linear_regression(X_train, y_train, r)

# Make predictions on the test dataset
y_pred = w0 + X_test.dot(w)

# Calculate RMSE on the test dataset
test_rmse = rmse(y_test, y_pred)
print("RMSE on the test dataset:", test_rmse)


RMSE on the test dataset: 69008.41096733189


<h1>Validation Code</h1>

In [65]:
#Question 1
missing_features = df.columns[df.isnull().any()].tolist()
print("Features with missing values:", missing_features)


Features with missing values: ['total_bedrooms']


In [66]:
#Question 2
median_population = np.median(df['population'])
print("Median population:", median_population)


Median population: 1166.0


In [67]:
#Question 3
# Prepare and split the dataset
# (Use the code you previously provided to prepare and split the dataset)

from sklearn.linear_model import LinearRegression

# Option 1: Fill missing values with 0
X_train_0 = X_train.copy()
X_val_0 = X_val.copy()
X_train_0[np.isnan(X_train_0)] = 0
X_val_0[np.isnan(X_val_0)] = 0

model_0 = LinearRegression()
model_0.fit(X_train_0, np.log1p(y_train))
y_pred_0 = model_0.predict(X_val_0)
rmse_0 = rmse(np.log1p(y_val), y_pred_0)

# Option 2: Fill missing values with the mean (computed from the training data)
mean_fill_value = np.nanmean(X_train, axis=0)
X_train_mean = X_train.copy()
X_val_mean = X_val.copy()

for i in range(X_train_mean.shape[1]):
    nan_indices_train = np.isnan(X_train_mean[:, i])
    nan_indices_val = np.isnan(X_val_mean[:, i])
    X_train_mean[nan_indices_train, i] = mean_fill_value[i]
    X_val_mean[nan_indices_val, i] = mean_fill_value[i]

model_mean = LinearRegression()
model_mean.fit(X_train_mean, np.log1p(y_train))
y_pred_mean = model_mean.predict(X_val_mean)
rmse_mean = rmse(np.log1p(y_val), y_pred_mean)

# Compare RMSE scores
print("RMSE with 0 fill:", round(rmse_0, 2))
print("RMSE with mean fill:", round(rmse_mean, 2))

# Determine which option gives better RMSE
if rmse_0 < rmse_mean:
    print("Option with 0 fill gives a better RMSE.")
elif rmse_mean < rmse_0:
    print("Option with mean fill gives a better RMSE.")
else:
    print("Both options are equally good.")


RMSE with 0 fill: 0.34
RMSE with mean fill: 0.34
Both options are equally good.


In [68]:
#Question 4
r_values = [0, 0.000001, 0.0001, 0.001, 0.01, 0.1, 1, 5, 10]
best_rmse = float('inf')
best_r = None

for r in r_values:
    X_train_r = X_train.copy()
    X_val_r = X_val.copy()
    
    # Fill NAs with 0
    X_train_r[np.isnan(X_train_r)] = 0
    X_val_r[np.isnan(X_val_r)] = 0
    
    # Train a regularized linear regression model
    w0_r, w_r = train_linear_regression(X_train_r, np.log1p(y_train), r)
    y_pred_r = w0_r + X_val_r.dot(w_r)
    
    # Calculate RMSE
    rmse_r = rmse(np.log1p(y_val), y_pred_r)
    
    # Check if this is the best RMSE so far
    if rmse_r < best_rmse:
        best_rmse = rmse_r
        best_r = r

# Round the RMSE scores to 2 decimal digits
best_rmse = round(best_rmse, 2)

print("Best r value:", best_r)
print("Best RMSE:", best_rmse)


Best r value: 0.01
Best RMSE: 0.34


In [69]:
#Question 5
seed_values = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
rmse_scores = []

for seed in seed_values:
    # Split the data with the current seed
    df_train, df_val, df_test = custom_split_data(df, seed=seed)
    
    # Combine train and validation datasets
    df_train = pd.concat([df_train, df_val], axis=0)
    
    # Extract target variables
    y_train = df_train['median_house_value'].values
    y_test = df_test['median_house_value'].values
    
    # Drop target variable from datasets
    df_train = df_train.drop(columns=['median_house_value'])
    df_test = df_test.drop(columns=['median_house_value'])
    
    # Prepare feature matrices X_train and X_test
    X_train = prepare_X(df_train)
    X_test = prepare_X(df_test)
    
    # Fill missing values with 0
    X_train[np.isnan(X_train)] = 0
    X_test[np.isnan(X_test)] = 0
    
    # Train a model without regularization
    w0_seed, w_seed = train_linear_regression(X_train, np.log1p(y_train), 0)
    y_pred_seed = w0_seed + X_test.dot(w_seed)
    
    # Calculate RMSE
    rmse_seed = rmse(np.log1p(y_test), y_pred_seed)
    rmse_scores.append(rmse_seed)

# Calculate the standard deviation of RMSE scores
std_deviation = np.std(rmse_scores)
std_deviation = round(std_deviation, 3)

print("Standard Deviation of RMSE scores:", std_deviation)


Standard Deviation of RMSE scores: 0.005


In [70]:
df.columns

Index(['latitude', 'longitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income',
       'median_house_value', 'ocean_proximity'],
      dtype='object')

In [71]:
# Step 1: Check the column names
print(df_train.columns)

# Step 2: Verify that the column exists in the DataFrame
if 'median_house_value' in df_train.columns:
    # Access the column
    y_train = df_train['median_house_value'].values
else:
    # Print an error message or handle the case where the column is missing
    print("Column 'median_house_value' not found in df_train.")

# Step 3: Repeat the same check for df_test if necessary
if 'median_house_value' in df_test.columns:
    # Access the column
    y_test = df_test['median_house_value'].values
else:
    # Print an error message or handle the case where the column is missing
    print("Column 'median_house_value' not found in df_test.")

# Step 4: Continue with your data processing and modeling code

# For example, you can continue with the following code:
# Fill missing values with 0 in both X_train and X_test
X_train[np.isnan(X_train)] = 0
X_test[np.isnan(X_test)] = 0



Index(['latitude', 'longitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income',
       'ocean_proximity'],
      dtype='object')
Column 'median_house_value' not found in df_train.
Column 'median_house_value' not found in df_test.


In [72]:
df_test.head()

latitude  longitude  housing_median_age  total_rooms  total_bedrooms  \
168       37.79    -122.24                27.0       1632.0           492.0   
17299     34.40    -119.51                15.0       1112.0           256.0   
10347     33.61    -117.66                21.0       1932.0           266.0   
846       37.58    -122.08                16.0       3349.0           544.0   
12920     38.66    -121.31                26.0       1604.0           245.0   

       population  households  median_income ocean_proximity  
168        1171.0       429.0         2.3173        NEAR BAY  
17299       411.0       245.0         2.0625      NEAR OCEAN  
10347       860.0       286.0         7.1497       <1H OCEAN  
846        2003.0       488.0         6.0074        NEAR BAY  
12920       751.0       267.0         4.7381          INLAND

In [73]:
print("X_train shape:", X_train.shape)
print("X_test shape:", X_test.shape)


X_train shape: (16512, 8)
X_test shape: (4128, 8)


In [103]:
#Question 6
import numpy as np
import pandas as pd
from sklearn.metrics import mean_squared_error

# Define the train_linear_regression function as before (please make sure it's defined earlier in your notebook)

def prepare_X(df):
    df = df.copy()
    df['total_bedrooms'].fillna(df['total_bedrooms'].median(), inplace=True)  # Fill missing values
    df['population'].fillna(df['population'].median(), inplace=True)  # Fill missing values
    df['housing_median_age'].fillna(df['housing_median_age'].median(), inplace=True)  # Fill missing values
    df = pd.get_dummies(df, columns=['ocean_proximity'], drop_first=True)  # One-hot encode categorical variable
    X = df.drop(columns=['median_house_value']).values  # Remove target variable and get feature matrix
    return X

# Set a random seed for reproducibility
seed = 9

# Split the dataset
np.random.seed(seed)
n = len(df)
n_val = int(0.2 * n)
n_test = int(0.2 * n)
n_train = n - n_val - n_test

idx = np.arange(n)
np.random.shuffle(idx)

df_shuffled = df.iloc[idx]
df_train = df_shuffled.iloc[:n_train].copy()
df_val = df_shuffled.iloc[n_train:n_train + n_val].copy()
df_test = df_shuffled.iloc[n_train + n_val:].copy()

# Combine train and validation datasets
df_train = pd.concat([df_train, df_val], axis=0)

# Ensure that 'median_house_value' column is included in df_train and df_test
if 'median_house_value' not in df_train.columns:
    raise KeyError("Column 'median_house_value' not found in df_train.")
if 'median_house_value' not in df_test.columns:
    # Handle the case where 'median_house_value' is not in df_test by adding it with NaN values
    df_test['median_house_value'] = np.nan

# Prepare feature matrices X_train and X_test
X_train = prepare_X(df_train)
X_test = prepare_X(df_test)

# Fill missing values with 0
X_train[np.isnan(X_train)] = 0
X_test[np.isnan(X_test)] = 0

# Extract the target variable 'median_house_value'
y_train = df_train['median_house_value'].values

# Train the model with r=0.001
w0_final, w_final = train_linear_regression(X_train, np.log1p(y_train), 0.001)

# Make predictions on the test dataset
y_pred_final = w0_final + X_test.dot(w_final)

# Calculate RMSE on the test dataset
test_rmse_final = np.sqrt(mean_squared_error(np.log1p(df_test['median_house_value'].values), y_pred_final))
test_rmse_final = round(test_rmse_final, 2)

print("RMSE on the test dataset:", test_rmse_final)
















RMSE on the test dataset: 0.33
